<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ContextualQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ─── VEHÍCULOS ───
            [
                'module' => 'fleet',
                'title' => 'Conteo de vehículos',
                'question_text' => '¿Cuántos vehículos tengo?',
                'patterns' => ['cuantos vehiculos', 'total vehiculos', 'cuantos carros', 'numero de vehiculos'],
                'response_type' => 'count',
                'response_template' => '🚛 Actualmente hay **{count}** vehículos registrados en la flota.',
                'entity_type' => 'vehicles',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 10,
            ],
            [
                'module' => 'fleet',
                'title' => 'Vehículos activos',
                'question_text' => 'Mostrar vehículos activos',
                'patterns' => ['vehiculos activos', 'vehiculos en servicio', 'flota activa', 'vehiculos habilitados'],
                'response_type' => 'list',
                'response_template' => "🚛 **{count}** vehículos activos:\n{results}",
                'entity_type' => 'vehicles',
                'filters' => ['is_active' => true],
                'expiring_days' => null,
                'sort_order' => 20,
            ],
            [
                'module' => 'fleet',
                'title' => 'Lista de vehículos',
                'question_text' => 'Listar todos los vehículos',
                'patterns' => ['lista de vehiculos', 'listar vehiculos', 'todos los vehiculos', 'ver vehiculos'],
                'response_type' => 'list',
                'response_template' => "🚛 **{count}** vehículos:\n{results}",
                'entity_type' => 'vehicles',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 30,
            ],

            // ─── SOAT / DOCUMENTOS ───
            [
                'module' => 'fleet',
                'title' => 'SOAT por vencer',
                'question_text' => '¿Qué SOAT están por vencer?',
                'patterns' => ['soat por vencer', 'soat vencido', 'seguro vehiculo vencido', 'soat proximo a vencer'],
                'response_type' => 'expiring',
                'response_template' => "📋 **{count}** SOAT próximos a vencer en {days} días:\n{results}",
                'entity_type' => 'vehicle_documents',
                'filters' => ['document_type' => 'SOAT'],
                'expiring_days' => 30,
                'sort_order' => 40,
            ],
            [
                'module' => 'fleet',
                'title' => 'RTM por vencer',
                'question_text' => '¿Qué RTM están por vencer?',
                'patterns' => ['rtm por vencer', 'rtm vencido', 'seguro vehiculo vencido', 'rtm proximo a vencer', 'tecnomecanica', 'Revision tecnomecanica', 'Reviso tecnomecanica', 'tecnomecanica vencida', 'tecnomecanica por vencer'],
                'response_type' => 'expiring',
                'response_template' => "📋 **{count}** RTM próximos a vencer en {days} días:\n{results}",
                'entity_type' => 'vehicle_documents',
                'filters' => ['document_type' => 'RTM'],
                'expiring_days' => 30,
                'sort_order' => 40,
            ],

            [
                'module' => 'fleet',
                'title' => 'Poliza Rcc y Rce por vencer',
                'question_text' => '¿Qué Poliza Rcc y Rce están por vencer?',
                'patterns' => ['poliza rcc', 'poliza rce', 'poliza por vencer', 'poliza vencida', 'poliza proximo a vencer'],
                'response_type' => 'expiring',
                'response_template' => "📋 **{count}** Poliza Rcc y Rce próximos a vencer en {days} días:\n{results}",
                'entity_type' => 'vehicle_documents',
                'filters' => ['document_type' => 'poliza rcc y rce'],
                'expiring_days' => 30,
                'sort_order' => 40,
            ],
            // ─── MANTENIMIENTOS ───
            [
                'module' => 'fleet',
                'title' => 'Próximos mantenimientos',
                'question_text' => 'Mostrar próximos mantenimientos',
                'patterns' => ['proximos mantenimientos', 'mantenimientos pendientes', 'mantenimiento programado', 'reparaciones pendientes'],
                'response_type' => 'list',
                'response_template' => "🔧 **{count}** mantenimientos registrados:\n{results}",
                'entity_type' => 'maintenances',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 50,
            ],
            // ─── LICENCIAS ───
            [
                'module' => 'fleet',
                'title' => 'Licencias por vencer',
                'question_text' => '¿Qué licencias están por vencer?',
                'patterns' => ['licencias por vencer', 'licencias vencidas', 'conduccion vencida', 'licencias proximo'],
                'response_type' => 'expiring',
                'response_template' => "🪪 **{count}** licencias próximas a vencer en {days} días:\n{results}",
                'entity_type' => 'driver_licenses',
                'filters' => null,
                'expiring_days' => 30,
                'sort_order' => 60,
            ],
            // ─── TARJETAS DE OPERACIÓN ───
            [
                'module' => 'fleet',
                'title' => 'Tarjetas de operación activas',
                'question_text' => 'Mostrar tarjetas de operación activas',
                'patterns' => ['tarjetas de operacion activas', 'tdo activas', 'tarjetas activas', 'tarjeta operacion vigente'],
                'response_type' => 'list',
                'response_template' => "🪪 **{count}** tarjetas de operación activas:\n{results}",
                'entity_type' => 'operation_cards',
                'filters' => ['status' => true],
                'expiring_days' => null,
                'sort_order' => 70,
            ],
            [
                'module' => 'fleet',
                'title' => 'Tarjetas de operación por vencer',
                'question_text' => 'Tarjetas de operación próximas a vencer',
                'patterns' => ['tarjetas por vencer', 'tdo por vencer', 'operacion por vencer'],
                'response_type' => 'expiring',
                'response_template' => "🪪 **{count}** tarjetas de operación por vencer en {days} días:\n{results}",
                'entity_type' => 'operation_cards',
                'filters' => null,
                'expiring_days' => 30,
                'sort_order' => 80,
            ],
            // ─── CONDUCTORES ───
            [
                'module' => 'fleet',
                'title' => 'Conteo de conductores',
                'question_text' => '¿Cuántos conductores hay?',
                'patterns' => ['cuantos conductores', 'total conductores', 'numero de conductores', 'conductores registrados'],
                'response_type' => 'count',
                'response_template' => '👤 Hay **{count}** conductores registrados en el sistema.',
                'entity_type' => 'owner_drivers',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 90,
            ],
            // ─── PROPIETARIOS ───
            [
                'module' => 'fleet',
                'title' => 'Propietarios de vehículos',
                'question_text' => 'Listar propietarios',
                'patterns' => ['propietarios', 'duenos de vehiculos', 'titulares', 'lista de propietarios'],
                'response_type' => 'list',
                'response_template' => "👤 **{count}** propietarios:\n{results}",
                'entity_type' => 'owners',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 100,
            ],
            // ─── TERCEROS / CLIENTES ───
            [
                'module' => 'third_parties',
                'title' => 'Conteo de clientes',
                'question_text' => '¿Cuántos clientes hay?',
                'patterns' => ['cuantos clientes', 'total clientes', 'numero de clientes', 'clientes registrados'],
                'response_type' => 'count',
                'response_template' => '👤 Hay **{count}** clientes registrados en el sistema.',
                'entity_type' => 'third_parties',
                'filters' => ['is_customer' => true],
                'expiring_days' => null,
                'sort_order' => 110,
            ],
            [
                'module' => 'third_parties',
                'title' => 'Lista de clientes',
                'question_text' => 'Listar todos los clientes',
                'patterns' => ['lista de clientes', 'listar clientes', 'todos los clientes', 'ver clientes'],
                'response_type' => 'list',
                'response_template' => "👤 **{count}** clientes:\n{results}",
                'entity_type' => 'third_parties',
                'filters' => ['is_customer' => true],
                'expiring_days' => null,
                'sort_order' => 120,
            ],
            // ─── CONTRATISTAS ───
            [
                'module' => 'third_parties',
                'title' => 'Contratistas activos',
                'question_text' => 'Listar contratistas activos',
                'patterns' => ['contratistas activos', 'proveedores activos', 'lista de contratistas', 'contratantes'],
                'response_type' => 'list',
                'response_template' => "📋 **{count}** contratistas activos:\n{results}",
                'entity_type' => 'contractors',
                'filters' => ['status' => true],
                'expiring_days' => null,
                'sort_order' => 130,
            ],
            // ─── FUECs / CONTRATOS ───
            [
                'module' => 'contract_extract',
                'title' => 'Últimos FUECs',
                'question_text' => 'Mostrar últimos FUECs registrados',
                'patterns' => ['ultimos fuecs', 'fuecs recientes', 'lista de fuecs', 'ver fuecs'],
                'response_type' => 'list',
                'response_template' => "📄 **{count}** FUECs registrados:\n{results}",
                'entity_type' => 'fuecs',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 140,
            ],
            [
                'module' => 'contract_extract',
                'title' => 'Conteo de FUECs activos',
                'question_text' => '¿Cuántos FUECs activos hay?',
                'patterns' => ['fuecs activos', 'contratos activos', 'fuecs vigentes', 'numero de fuecs'],
                'response_type' => 'count',
                'response_template' => '📄 Hay **{count}** FUECs registrados en el sistema.',
                'entity_type' => 'fuecs',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 150,
            ],
            [
                'module' => 'contract_extract',
                'title' => 'Contratos por vencer',
                'question_text' => 'FUECs próximos a vencer',
                'patterns' => ['contratos por vencer', 'fuecs por vencer', 'extractos vencidos', 'viajes por vencer'],
                'response_type' => 'expiring',
                'response_template' => "📄 **{count}** contratos próximos a vencer en {days} días:\n{results}",
                'entity_type' => 'fuecs',
                'filters' => null,
                'expiring_days' => 30,
                'sort_order' => 160,
            ],
            // ─── SUCURSALES ───
            [
                'module' => 'administration',
                'title' => 'Lista de sucursales',
                'question_text' => 'Listar sucursales registradas',
                'patterns' => ['sucursales', 'sedes', 'lista de sucursales', 'oficinas', 'puntos de atencion'],
                'response_type' => 'list',
                'response_template' => "🏢 **{count}** sucursales:\n{results}",
                'entity_type' => 'branches',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 170,
            ],
            [
                'module' => 'administration',
                'title' => 'Conteo de sucursales',
                'question_text' => '¿Cuántas sucursales hay?',
                'patterns' => ['cuantas sucursales', 'total sucursales', 'numero de sucursales'],
                'response_type' => 'count',
                'response_template' => '🏢 Hay **{count}** sucursales registradas.',
                'entity_type' => 'branches',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 180,
            ],
            // ─── INSPECCIONES ───
            [
                'module' => 'fleet',
                'title' => 'Inspecciones recientes',
                'question_text' => 'Mostrar inspecciones recientes',
                'patterns' => ['inspecciones recientes', 'ultimas inspecciones', 'checklist vehiculos', 'revisiones'],
                'response_type' => 'list',
                'response_template' => "🔍 **{count}** inspecciones:\n{results}",
                'entity_type' => 'inspections',
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 190,
            ],
            // ─── AYUDA GENERAL ───
            [
                'module' => 'general',
                'title' => 'Ayuda / Qué puedes hacer',
                'question_text' => '¿Qué puedes hacer?',
                'patterns' => ['que puedes hacer', 'ayuda', 'funciones', 'comandos', 'que haces', 'como funciona'],
                'response_type' => 'text',
                'response_template' => "🤖 **Hola, soy tu asistente Next**\n\nPuedo ayudarte con:\n\n🚛 **Vehículos**: contar, listar, activos, SOAT por vencer\n👤 **Terceros**: clientes, conductores, contratistas\n📄 **FUECs**: contratos activos, próximos a vencer\n🏢 **Sucursales**: listar, contar\n🔧 **Mantenimientos**: próximos, pendientes\n🪪 **Licencias y TDO**: vigentes, por vencer\n\n✅ Ejemplos de preguntas:\n\"cuántos vehículos tengo\"\n\"lista de clientes\"\n\"SOAT por vencer\"\n\"vehículos activos\"\n\"sucursales\"",
                'entity_type' => null,
                'filters' => null,
                'expiring_days' => null,
                'sort_order' => 0,
            ],
        ];

        $now = now();

        foreach ($questions as $data) {
            DB::table('contextual_questions')->insert([
                'uuid' => (string) Str::uuid(),
                'module' => $data['module'],
                'title' => $data['title'],
                'question_text' => $data['question_text'],
                'patterns' => json_encode($data['patterns'], JSON_UNESCAPED_UNICODE),
                'response_type' => $data['response_type'],
                'response_template' => $data['response_template'],
                'entity_type' => $data['entity_type'],
                'filters' => $data['filters'] !== null ? json_encode($data['filters'], JSON_UNESCAPED_UNICODE) : null,
                'expiring_days' => $data['expiring_days'],
                'sort_order' => $data['sort_order'],
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
